set number
set linebreak
set showbreak=+++
set textwidth=238
set showmatch
set errorbells
set visualbell
set hlsearch
set smartcase
set incsearch
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set ruler
set undolevels=1000
set backspace=indent,eol,start
colors koehler
syntax enable
